import Head from 'next/head'
import {Inter} from '@next/font/google'
import styles from '@/styles/Home.module.css'
import {Share} from "@capacitor/share";
import {IonButton, IonHeader, IonTitle, IonToolbar} from "@ionic/react";

const inter = Inter({subsets: ['latin']})

export default function Home() {

    const share = async () => {
        await Share.share({
            title: 'See cool stuff',
            text: 'Really awesome thing you need to see right meow',
            url: 'http://ionicframework.com/',
            dialogTitle: 'Share with buddies',
        });
    }

    return (
        <>
            <Head>
                <title>Next & Capacitor</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <IonHeader>
                <IonToolbar color="tertiary">
                    <IonTitle style={{paddingLeft: '16px'}}>
                        Next & Capacitor
                    </IonTitle>
                </IonToolbar>
            </IonHeader>
            <main className={styles.main}>
                <div className={styles.center}>
                    <h1 className={styles.title}>
                        Next.js & Capacitor
                    </h1>
                    <IonButton onClick={() => share()} color="tertiary">
                        Interact with the Device
                    </IonButton>
                </div>
            </main>
        </>
    )
}
